
export default new Map([
["src/content/blog/crypto-options.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fcrypto-options.mdx&astroContentModuleFlag=true")],
["src/content/blog/emission-trading-system.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Femission-trading-system.mdx&astroContentModuleFlag=true")],
["src/content/blog/interactive-cfd.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Finteractive-cfd.mdx&astroContentModuleFlag=true")],
["src/content/blog/the-most-used-ais.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fthe-most-used-ais.mdx&astroContentModuleFlag=true")],
["src/content/blog/uk-power-market.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fuk-power-market.mdx&astroContentModuleFlag=true")],
["src/content/coding/inter-core-communication.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fcoding%2Finter-core-communication.mdx&astroContentModuleFlag=true")],
["src/content/coding/rust-for-hft.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fcoding%2Frust-for-hft.mdx&astroContentModuleFlag=true")],
["src/content/lab/agnesi.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Flab%2Fagnesi.mdx&astroContentModuleFlag=true")],
["src/content/lab/binary-tree.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Flab%2Fbinary-tree.mdx&astroContentModuleFlag=true")],
["src/content/lab/country-stats.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Flab%2Fcountry-stats.mdx&astroContentModuleFlag=true")],
["src/content/lab/cylinder.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Flab%2Fcylinder.mdx&astroContentModuleFlag=true")],
["src/content/lab/eurostat.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Flab%2Feurostat.mdx&astroContentModuleFlag=true")],
["src/content/lab/flow-field.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Flab%2Fflow-field.mdx&astroContentModuleFlag=true")],
["src/content/lab/game-of-life.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Flab%2Fgame-of-life.mdx&astroContentModuleFlag=true")],
["src/content/lab/largest-area-in-histogram.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Flab%2Flargest-area-in-histogram.mdx&astroContentModuleFlag=true")],
["src/content/lab/logo-circles.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Flab%2Flogo-circles.mdx&astroContentModuleFlag=true")],
["src/content/lab/logo-voronoi.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Flab%2Flogo-voronoi.mdx&astroContentModuleFlag=true")],
["src/content/lab/mandelbrot-set.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Flab%2Fmandelbrot-set.mdx&astroContentModuleFlag=true")],
["src/content/lab/pi.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Flab%2Fpi.mdx&astroContentModuleFlag=true")],
["src/content/lab/planarity.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Flab%2Fplanarity.mdx&astroContentModuleFlag=true")],
["src/content/lab/population-density-europe.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Flab%2Fpopulation-density-europe.mdx&astroContentModuleFlag=true")],
["src/content/lab/rotating-world.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Flab%2Frotating-world.mdx&astroContentModuleFlag=true")],
["src/content/lab/sparkling.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Flab%2Fsparkling.mdx&astroContentModuleFlag=true")],
["src/content/lab/tradingview.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Flab%2Ftradingview.mdx&astroContentModuleFlag=true")]]);
		