[workspace]
resolver = "3"
members = [
    "lsrs/*",
]
default-members = [
  "lsrs/*",
]


[workspace.package]
version = "0.1.0"
authors = ["Luca Sbardella <luca@quantmind.com>"]
edition = "2024"
repository = "https://github.com/lsbardel/lucasbardella.com"


[workspace.dependencies]
rtrb = "0.3.2"
