[project]
name = "lucasbardella-com"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.2"
dependencies = [
    "aio-fluid[cli,http]>=1.5.0",
    "qrcode[pil]>=8.0",
]
