"""Generate the LaTeX CV sources from ``content/cv.md``.

``content/cv.md`` is the single source of truth for the CV. This module parses
its ``Work Experience`` and ``Education`` sections and writes the LaTeX include
files consumed by ``make cv`` to build the PDF, so the downloadable PDF can
never drift from the web page.

The PDF is a skim of the same material rather than a copy of it, so each entry
is condensed on the way out:

* only the lead paragraph of an entry is carried over, any following paragraphs
  are web only
* ``Coding`` and ``Technologies`` are merged into a single line and
  ``Specialities`` is dropped, it earns its place on the web for search but is
  dead weight in print
* links become plain text, a printed CV has nothing to click

Generated files must not be edited by hand. Edit ``content/cv.md`` and run
``make cv-sync``. The header, skills and document sections of the PDF have no
equivalent on the web page and stay hand maintained in ``cv/header.tex``,
``cv/skills.tex`` and ``cv/luca-sbardella-cv.tex``.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CV_MARKDOWN = ROOT / "content" / "cv.md"
CV_DIR = ROOT / "cv"
SITE_URL = "https://lucasbardella.com"

#: markdown section heading mapped to the LaTeX file it generates
SECTIONS = {
    "Work Experience": "employment.tex",
    "Education": "academic.tex",
}

#: meta lines the PDF leaves to the web page
SKIPPED_META = ("Specialities",)

#: meta lines the PDF merges into a single ``Technologies`` line
MERGED_META = ("Coding", "Technologies", "Technology")

BANNER = (
    "% Generated by `make cv-sync` from content/cv.md.\n"
    "% Do not edit by hand: edit content/cv.md and run `make cv-sync`.\n"
)

MONTHS = (
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
)

SECTION_RE = re.compile(r"^##\s+(?P<name>.+?)\s*$")
ENTRY_RE = re.compile(r"^###\s+(?P<heading>.+?)\s*$")
META_RE = re.compile(r"^\*\*(?P<key>[^*]+)\*\*:\s*(?P<value>.+?)\s*$")
DATE_RE = re.compile(r"^\*\*(?P<dates>[^*]+)\*\*\s*(?:-\s*)?(?P<location>.*?)\s*$")
LINK_REF_RE = re.compile(r"^\[[^\]]+\]:\s")
NOTE_RE = re.compile(r"\s*\((?P<note>[^)]+)\)\s*$")
INLINE_RE = re.compile(
    r"\[(?P<text>[^\]]+)\]\((?P<url>[^)]+)\)|\*\*(?P<bold>[^*]+)\*\*"
)

LATEX_SPECIALS = {
    "\\": r"\textbackslash{}",
    "&": r"\&",
    "%": r"\%",
    "$": r"\$",
    "#": r"\#",
    "_": r"\_",
    "{": r"\{",
    "}": r"\}",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
}


@dataclass
class Entry:
    """A single CV entry, either a role or a qualification."""

    title: str = ""
    organisation: str = ""
    dates: str = ""
    note: str = ""
    location: str = ""
    body: list[str] = field(default_factory=list)
    meta: list[tuple[str, str]] = field(default_factory=list)


def escape(text: str) -> str:
    """Escape LaTeX special characters in plain text."""
    escaped = "".join(LATEX_SPECIALS.get(char, char) for char in text)
    return escaped.replace("–", "--").replace("—", "---")


def md_to_tex(text: str) -> str:
    """Convert inline markdown to LaTeX, escaping the rest.

    Inline markup is flattened to plain text. Links lose their URL because
    print has nothing to click, and emphasis is dropped because the entry
    headings already carry the weight on the page.
    """
    text = re.sub(r"<br\s*/?>", "", text)
    parts: list[str] = []
    position = 0
    for match in INLINE_RE.finditer(text):
        parts.append(escape(text[position : match.start()]))
        parts.append(escape(match.group("bold") or match.group("text")))
        position = match.end()
    parts.append(escape(text[position:]))
    return "".join(parts).strip()


def split_heading(heading: str) -> tuple[str, str]:
    """Split ``Title - [Organisation](url)`` into its title and organisation.

    Titles may themselves contain a separator, as in
    ``Director - Quantitative Analyst - [Citi](url)``, so the split is made on
    the last separator. Headings without one are treated as organisation only.
    """
    title, separator, organisation = heading.rpartition(" - ")
    if not separator:
        return "", strip_links(heading)
    return strip_links(title), strip_links(organisation)


def strip_links(text: str) -> str:
    """Replace markdown links with their display text."""
    return INLINE_RE.sub(lambda m: m.group("text") or m.group("bold") or "", text)


def strip_break(text: str) -> str:
    """Remove a trailing markdown line break."""
    return re.sub(r"<br\s*/?>\s*$", "", text).strip()


def short_dates(dates: str) -> tuple[str, str]:
    """Abbreviate month names and pull out any trailing parenthetical note."""
    note = ""
    if match := NOTE_RE.search(dates):
        note = match.group("note")
        dates = dates[: match.start()]
    dates = dates.replace("–", "-").replace("—", "-")
    for month in MONTHS:
        dates = re.sub(rf"\b{month}\b", month[:3], dates)
    return re.sub(r"\s*-\s*", " - ", dates).strip(), note.strip()


def short_location(location: str) -> str:
    """Reduce ``London, UK`` style locations to the city."""
    city = location.split(",")[0].split(" - ")[0].strip()
    return re.sub(r"\s+UK$", "", city).strip()


def parse_entry(heading: str, lines: list[str]) -> Entry:
    """Build an entry from its heading and the lines that follow it."""
    title, organisation = split_heading(heading)
    entry = Entry(title=title, organisation=organisation)
    paragraph: list[str] = []
    dates_found = False

    def flush() -> None:
        if paragraph:
            entry.body.append(" ".join(paragraph))
            paragraph.clear()

    for line in lines:
        stripped = line.strip()
        if not stripped or stripped == "<hr>" or LINK_REF_RE.match(stripped):
            flush()
            continue
        if match := META_RE.match(stripped):
            flush()
            entry.meta.append((match.group("key"), strip_break(match.group("value"))))
            continue
        if not dates_found and (match := DATE_RE.match(stripped)):
            flush()
            dates_found = True
            entry.dates, entry.note = short_dates(match.group("dates"))
            entry.location = short_location(match.group("location"))
            continue
        paragraph.append(strip_break(stripped))
    flush()
    return entry


def parse(text: str) -> dict[str, list[Entry]]:
    """Parse the CV markdown into entries keyed by section heading."""
    sections: dict[str, list[Entry]] = {name: [] for name in SECTIONS}
    section: str | None = None
    heading: str | None = None
    buffer: list[str] = []

    def flush() -> None:
        nonlocal heading
        if section in sections and heading is not None:
            sections[section].append(parse_entry(heading, buffer))
        heading = None
        buffer.clear()

    for line in text.splitlines():
        if match := SECTION_RE.match(line):
            flush()
            section = match.group("name")
            continue
        if match := ENTRY_RE.match(line):
            flush()
            heading = match.group("heading")
            continue
        if heading is not None:
            buffer.append(line)
    flush()
    return sections


def pdf_meta(meta: list[tuple[str, str]]) -> list[tuple[str, str]]:
    """Condense the web meta lines down to what belongs in print."""
    kept: list[tuple[str, str]] = []
    merged: list[str] = []
    for key, value in meta:
        if key in SKIPPED_META:
            continue
        if key in MERGED_META:
            merged.extend(item.strip() for item in value.split(",") if item.strip())
            continue
        kept.append((key, value))
    if merged:
        kept.append(("Technologies", ", ".join(dict.fromkeys(merged))))
    return kept


def render_entry(entry: Entry) -> str:
    """Render one entry as a ``cvevent`` block."""
    # entries without a role title, such as qualifications, lead with the
    # organisation so the event line never starts with an empty field
    title = entry.title or entry.organisation
    organisation = entry.organisation if entry.title else ""
    lines = [
        "\\cvevent{%s}{%s}{%s}{%s}"
        % (
            md_to_tex(entry.dates),
            md_to_tex(title),
            md_to_tex(organisation),
            md_to_tex(entry.location),
        )
    ]
    if entry.note:
        lines.append("")
        lines.append(rf"{{\bf {md_to_tex(entry.note)}}}")
    # only the lead paragraph makes it into print, the rest is web only
    for paragraph in entry.body[:1]:
        lines.append("")
        lines.append(md_to_tex(paragraph))
    for key, value in pdf_meta(entry.meta):
        lines.append("")
        lines.append(rf"{{\it {md_to_tex(key)}}}: {md_to_tex(value)}")
    return "\n".join(lines)


def render(entries: list[Entry]) -> str:
    """Render a whole section."""
    blocks = "\n\n".join(render_entry(entry) for entry in entries)
    return f"{BANNER}\n{blocks}\n"


def sync(source: Path = CV_MARKDOWN, target: Path = CV_DIR) -> list[Path]:
    """Generate the LaTeX sources from the CV markdown, returning what changed."""
    sections = parse(source.read_text())
    written: list[Path] = []
    for name, filename in SECTIONS.items():
        entries = sections.get(name, [])
        if not entries:
            raise ValueError(f"no entries found in the '{name}' section of {source}")
        path = target / filename
        content = render(entries)
        if not path.exists() or path.read_text() != content:
            path.write_text(content)
            written.append(path)
    return written
