// Generated by lsts/heatmap-sources.ts, run `make heatmap-sources` to refresh.
// Extracted from the TradingView stock heatmap widget bundle, which ships the
// DataSets enum, a description map and a dataset/country map. There is no
// public API for this list. Do not edit by hand.
// 111 markets across 35 groups.

export interface HeatmapSource {
  value: string;
  label: string;
}

export interface HeatmapSourceGroup {
  country: string;
  sources: HeatmapSource[];
}

export const SOURCE_GROUPS: HeatmapSourceGroup[] = [
  {
    country: "United States",
    sources: [
      { value: "SPX500", label: "S&P 500 Index" },
      { value: "NASDAQ100", label: "NASDAQ 100 Index" },
      { value: "NASDAQCOMPOSITE", label: "NASDAQ Composite Index" },
      { value: "DJCA", label: "Dow Jones Composite Average Index" },
      { value: "DJDJI", label: "Dow Jones Industrial Average Index" },
      { value: "DJDJT", label: "Dow Jones Transportation Average Index" },
      { value: "DJDJU", label: "Dow Jones Utility Average Index" },
      { value: "NASDAQBKX", label: "KBW NASDAQ Bank Index" },
      { value: "TVCRUI", label: "Russell 1000 Index" },
      { value: "TVCRUT", label: "Russell 2000 Index" },
      { value: "TVCRUA", label: "Russell 3000 Index" },
      { value: "AllUSA", label: "All US companies" },
    ],
  },
  {
    country: "Argentina",
    sources: [
      { value: "BCBAIMV", label: "S&P MERVAL Index" },
      { value: "AllAR", label: "All Argentinean companies" },
    ],
  },
  {
    country: "Australia",
    sources: [
      { value: "AllAU", label: "All Australian companies" },
      { value: "ASX200", label: "S&P/ASX 200 Index" },
    ],
  },
  {
    country: "Brazil",
    sources: [
      { value: "IBOV", label: "Bovespa Index" },
      { value: "IBXL", label: "Brazil 50 Index" },
      { value: "AllBR", label: "All Brazilian companies" },
    ],
  },
  {
    country: "Canada",
    sources: [
      { value: "AllCA", label: "All Canadian companies" },
    ],
  },
  {
    country: "Chile",
    sources: [
      { value: "AllCL", label: "All Chilean companies" },
    ],
  },
  {
    country: "Colombia",
    sources: [
      { value: "BVCICAP", label: "MSCI COLCAP Index" },
      { value: "AllCO", label: "All Colombian companies" },
    ],
  },
  {
    country: "Cyprus",
    sources: [
      { value: "CSECYALTE", label: "CSE Alternative Market Index" },
      { value: "CSECYMAIN", label: "CSE Main Market Index" },
      { value: "CSECYGEN", label: "CSE General Index" },
      { value: "CSECYHOTEL", label: "CSE Hotels Index" },
      { value: "CSECYFTSE20", label: "FTSE/CySE 20 Index" },
      { value: "AllCY", label: "All Cyprus companies" },
    ],
  },
  {
    country: "Denmark",
    sources: [
      { value: "OMXCOPOMXC25", label: "OMX Copenhagen 25 Index" },
      { value: "AllDK", label: "All Danish companies" },
    ],
  },
  {
    country: "Egypt",
    sources: [
      { value: "EGXEGX30", label: "EGX 30 Index" },
      { value: "AllEG", label: "All Egyptian companies" },
    ],
  },
  {
    country: "Estonia",
    sources: [
      { value: "OMXTSEOMXTGI", label: "OMX Tallinn Gross Index" },
      { value: "AllEE", label: "All Estonian companies" },
    ],
  },
  {
    country: "Finland",
    sources: [
      { value: "HELSINKI25", label: "OMX Helsinki 25 Index" },
      { value: "AllFI", label: "All Finnish companies" },
    ],
  },
  {
    country: "Germany",
    sources: [
      { value: "DAX", label: "DAX Index" },
      { value: "MDAX", label: "MDAX Index" },
      { value: "SDAX", label: "SDAX Index" },
      { value: "TECDAX", label: "TecDAX Index" },
      { value: "AllDE", label: "All German companies" },
    ],
  },
  {
    country: "Greece",
    sources: [
      { value: "ATHEXGD", label: "ATHEX Composite Index" },
      { value: "ATHEXFTSEA", label: "FTSE/ATHEX Market Index" },
      { value: "ATHEXFTSEM", label: "FTSE/ATHEX Mid Cap Index" },
      { value: "ATHEXFTSE", label: "FTSE/ATHEX Large Cap Index" },
      { value: "AllGRC", label: "All Greek companies" },
    ],
  },
  {
    country: "Hong Kong",
    sources: [
      { value: "HSTECH", label: "Hang Seng Tech Index" },
      { value: "HSCEI", label: "Hang Seng China Enterprises Index" },
    ],
  },
  {
    country: "Hungary",
    sources: [
      { value: "BETBUX", label: "Budapest Stock Exchange Index" },
      { value: "AllHU", label: "All Hungarian companies" },
    ],
  },
  {
    country: "Iceland",
    sources: [
      { value: "OMXICEOMXI15", label: "OMX Iceland 15 Index" },
      { value: "AllIS", label: "All Icelandic companies" },
    ],
  },
  {
    country: "India",
    sources: [
      { value: "SENSEX", label: "S&P BSE SENSEX Index" },
    ],
  },
  {
    country: "Indonesia",
    sources: [
      { value: "IDX30", label: "IDX 30 Index" },
      { value: "IDXBUMN20", label: "IDX BUMN20 Index" },
      { value: "SRIKEHATI", label: "SRI-KEHATI" },
      { value: "IDXHIDIV20", label: "IDX High Dividend 20 Index" },
      { value: "AllID", label: "All Indonesian companies" },
    ],
  },
  {
    country: "Israel",
    sources: [
      { value: "TA35", label: "TA-35 Index" },
      { value: "TA125", label: "TA-125 Index" },
      { value: "AllIL", label: "All Israeli companies" },
    ],
  },
  {
    country: "Italy",
    sources: [
      { value: "FTSEMIB", label: "FTSE MIB Index" },
      { value: "AllIT", label: "All Italian companies" },
    ],
  },
  {
    country: "Kuwait",
    sources: [
      { value: "KSEBKA", label: "Boursa Kuwait All Share Index" },
      { value: "KSEBKM50", label: "Boursa Kuwait Main Market 50 Index" },
      { value: "KSEBKM", label: "Boursa Kuwait Main Market Index" },
      { value: "KSEBKP", label: "Boursa Kuwait Premier Market Index" },
      { value: "AllKW", label: "All Kuwaiti companies" },
    ],
  },
  {
    country: "Latvia",
    sources: [
      { value: "OMXRSEOMXRGI", label: "OMX Riga Gross Index" },
      { value: "AllLV", label: "All Latvian companies" },
    ],
  },
  {
    country: "Lithuania",
    sources: [
      { value: "OMXVSEOMXVGI", label: "OMX Vilnius Gross Index" },
      { value: "AllLT", label: "All Lithuanian companies" },
    ],
  },
  {
    country: "Mexico",
    sources: [
      { value: "F4GBIVA", label: "FTSE4Good BIVA Index" },
      { value: "FTBIVA", label: "FTSE BIVA Index" },
    ],
  },
  {
    country: "Morocco",
    sources: [
      { value: "CSEMAMASI", label: "MASI Index" },
      { value: "AllMA", label: "All Moroccan companies" },
    ],
  },
  {
    country: "Nigeria",
    sources: [
      { value: "NSENGNGX30", label: "NGX 30 Index" },
      { value: "AllNGA", label: "All Nigerian companies" },
    ],
  },
  {
    country: "Pakistan",
    sources: [
      { value: "PSXBKTI", label: "PSX Banking Sector Tradable Index" },
      { value: "PSXJSMFI", label: "JS Momentum Factor Index" },
      { value: "PSXKMI30", label: "KMI 30 Index" },
      { value: "PSXKSE30", label: "KSE 30 Index" },
      { value: "PSXKSE100", label: "KSE 100 Index" },
      { value: "PSXKMIALLSHR", label: "PSX-KMI All Share Index" },
      { value: "PSXALLSHR", label: "KSE All Share Index" },
      { value: "PSXMZNPI", label: "Meezan Pakistan Index" },
      { value: "PSXNBPPGI", label: "NBP Pakistan Growth Index" },
      { value: "PSXNITPGI", label: "NIT Pakistan Gateway Index" },
      { value: "PSXOGTI", label: "PSX Oil & Gas Tradable Sector Index" },
      { value: "PSXUPP9", label: "UBL Pakistan Enterprise Index" },
      { value: "AllPK", label: "All Pakistani companies" },
    ],
  },
  {
    country: "Poland",
    sources: [
      { value: "GPWWIG20", label: "WIG20 Index" },
      { value: "AllPO", label: "All Polish companies" },
    ],
  },
  {
    country: "Romania",
    sources: [
      { value: "BVBBET", label: "Bucharest Exchange Trading Index" },
      { value: "AllRO", label: "All Romanian companies" },
    ],
  },
  {
    country: "Spain",
    sources: [
      { value: "IBEX35", label: "IBEX 35 Index" },
      { value: "BMEIS", label: "IBEX Small Cap Index" },
      { value: "BMEICC", label: "IBEX Medium Cap Index" },
      { value: "BMEINDGRO15", label: "IBEX Growth Market 15 Index" },
      { value: "BMEINDGROAS", label: "IBEX Growth Market All Share Index" },
      { value: "AllES", label: "All Spanish companies" },
    ],
  },
  {
    country: "Sweden",
    sources: [
      { value: "OMXS30", label: "OMX Stockholm 30 Index" },
      { value: "AllSWE", label: "All Swedish companies" },
    ],
  },
  {
    country: "Switzerland",
    sources: [
      { value: "SIXSMI", label: "Swiss Market Index" },
      { value: "AllCHE", label: "All Swiss companies" },
    ],
  },
  {
    country: "UAE",
    sources: [
      { value: "ADXFADX15", label: "FTSE ADX 15 Index" },
    ],
  },
  {
    country: "Venezuela",
    sources: [
      { value: "BVCVIFINANCIE", label: "Financial Index" },
      { value: "BVCVIBC", label: "IBC index" },
      { value: "BVCVIINDUSTR", label: "Industrial Index" },
      { value: "AllVE", label: "All Venezuelan companies" },
    ],
  },
];

/** Flat lookup used to validate a source coming from the query string. */
export const SOURCE_VALUES = new Set<string>(
  SOURCE_GROUPS.flatMap((group) => group.sources.map((source) => source.value)),
);
