name: deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      METABLOCK_API_TOKEN: ${{ secrets.METABLOCK_API_TOKEN }}
      METABLOCK_BLOCK_ID: 2358b53a0557468d83d821445b4b5455

    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: build bundle
        run: yarn && yarn build
      - uses: quantmind/metablock-action@v3
        id: metablock-deployment-stage
        if: github.event_name == 'pull_request'
        with:
          env: stage
          bundle: static
      - uses: quantmind/metablock-action@v3
        id: metablock-deployment-prod
        if: github.event_name == 'push'
        with:
          env: prod
          bundle: static
