name: deploy

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: install uv
        run: pip install uv
      - name: build bundle
        env:
          GITHUB_RUN_ID: ${{ github.run_id }}
          GA_MEASUREMENT_ID: ${{ vars.GA_MEASUREMENT_ID }}
          GA_PROPERTY_ID: ${{ vars.GA_PROPERTY_ID }}
          GA_CLIENT_EMAIL: ${{ secrets.GA_CLIENT_EMAIL }}
          GA_PRIVATE_KEY: ${{ secrets.GA_PRIVATE_KEY }}
          FMP_API_KEY: ${{ secrets.FMP_API_KEY }}
        run: npm i && npm run build
      - name: upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      contents: read # to read the artifact
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

      # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: publish
        uses: actions/deploy-pages@v4
